### ISSUE TITLE
function sals_session_store_get(unknown) does not exist

### ISSUE THREAD

**Issue by ractoon** [ArekSredzki/electron-release-server#7]
Hi There,

Really appreciate this package, should make things much easier.

I'm running into an odd issue when running `npm start` on the server:

error:` sails-pg-session#get -  error: function sails_session_store_get(unknown) does not exist
    at Connection.parseE (/usr/share/nginx/html/electron-release-server/node_modules/sails-pg-session/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/usr/share/nginx/html/electron-release-server/node_modules/sails-pg-session/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/usr/share/nginx/html/electron-release-server/node_modules/sails-pg-session/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20) { [error: function sails_session_store_get(unknown) does not exist]
  name: 'error',
  length: 218,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '22',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '306',
  routine: 'ParseFuncOrColumn' }

All the services appear to be running and accessible, so not sure if I missed something in config.

**Comment by ArekSredzki** [comment]
Hi @ractoon, thanks for reaching out!

I forgot to include that you must follow the install instructions for [sails-pg-session](https://github.com/ravitej91/sails-pg-session). You must install some functions in your database.

I'll add this to the documentation now. Let me know if you have any further troubles :)

**Comment by ractoon** [comment]
That was it - thanks! 

Everything's setting up now but getting a "Login Successful" followed by a "Unauthorized, please login" message that I'm digging into as well.

**Comment by ArekSredzki** [comment]
@ractoon Glad to hear that part of the problem was solved. Let me know how this new issue progresses.

**Comment by ractoon** [comment]
@ArekSredzki Sure thing, was able to get everything up and running. The issue with the auth turned out to be in /api/controllers/AuthController.js on line 22/24 where it was looking for the "sAMAccountName" parameter for the user.

However, on my setup I didn't have that parameter so just modified that to use "user.uid" instead and everything hooking in.

Thanks again!

**Comment by beliaev-maksim** [comment]
@ArekSredzki 
Hi,
can you please suggest what can cause an issue?
I followed the instruction but still see an issue on Win10 machine

```
electron_release_server=> \conninfo
You are connected to database "electron_release_server" as user "electron_release_server_user" on host "localhost" at port "5432".
```

```
C:\GIT\sails-pg>"C:\Program Files\PostgreSQL\9.5\bin\psql.exe" electron_release_server_sessions < ./sql/sails-pg-session-support.sql postgres
ERROR:  relation "sails_session_store" already exists
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
```

session.js
```
module.exports.session = {
  // XXX: Enable this if you are using postgres as your database
  // If so, be sure to run the sql command detailed here: https://github.com/ravitej91/sails-pg-session
  adapter: 'sails-pg-session',
  database: 'electron_release_server',
    host: 'localhost',
    user: 'electron_release_server_user',
    password: '*****',
    port: 5432
};
```


and error on run:
```
error: sails-pg-session#get -  error: function sails_session_store_get(unknown) does not exist
    at Connection.parseE (C:\GIT\Electron_Server\node_modules\sails-pg-session\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (C:\GIT\Electron_Server\node_modules\sails-pg-session\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (C:\GIT\Electron_Server\node_modules\sails-pg-session\node_modules\pg\lib\connection.js:105:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
error: Error occurred in session middleware :: 'error: function sails_session_store_get(unknown) does not exist\n' +
  '    at Connection.parseE (C:\\GIT\\Electron_Server\\node_modules\\sails-pg-session\\node_modules\\pg\\lib\\connection.js:539:11)\n' +
  '    at Connection.parseMessage (C:\\GIT\\Electron_Server\\node_modules\\sails-pg-session\\node_modules\\pg\\lib\\connection.js:366:17)\n' +
  '    at Socket.<anonymous> (C:\\GIT\\Electron_Server\\node_modules\\sails-pg-session\\node_modules\\pg\\lib\\connection.js:105:22)\n' +
  '    at Socket.emit (events.js:315:20)\n' +
  '    at Socket.EventEmitter.emit (domain.js:482:12)\n' +
  '    at addChunk (_stream_readable.js:295:12)\n' +
  '    at readableAddChunk (_stream_readable.js:271:9)\n' +
  '    at Socket.Readable.push (_stream_readable.js:212:10)\n' +
  '    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)'
```

**Comment by beliaev-maksim** [comment]
for sanity check I tried with both:
v2land-sails-pg-session
sails-pg-session

the same error
```
error: sails-pg-session#get -  error: function sails_session_store_get(unknown) does not exist
    at Connection.parseE (C:\GIT\Electron_Server\node_modules\v2land-sails-pg-session\node_modules\pg\lib\connection.js:614:13)
    at Connection.parseMessage (C:\GIT\Electron_Server\node_modules\v2land-sails-pg-session\node_modules\pg\lib\connection.js:413:19)
    at Socket.<anonymous> (C:\GIT\Electron_Server\node_modules\v2land-sails-pg-session\node_modules\pg\lib\connection.js:129:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
error: Error occurred in session middleware :: 'error: function sails_session_store_get(unknown) does not exist\n' +
  '    at Connection.parseE (C:\\GIT\\Electron_Server\\node_modules\\v2land-sails-pg-session\\node_modules\\pg\\lib\\connection.js:614:13)\n' +
  '    at Connection.parseMessage (C:\\GIT\\Electron_Server\\node_modules\\v2land-sails-pg-session\\node_modules\\pg\\lib\\connection.js:413:19)\n' +
  '    at Socket.<anonymous> (C:\\GIT\\Electron_Server\\node_modules\\v2land-sails-pg-session\\node_modules\\pg\\lib\\connection.js:129:22)\n' +
  '    at Socket.emit (events.js:315:20)\n' +
  '    at Socket.EventEmitter.emit (domain.js:482:12)\n' +
  '    at addChunk (_stream_readable.js:295:12)\n' +
  '    at readableAddChunk (_stream_readable.js:271:9)\n' +
  '    at Socket.Readable.push (_stream_readable.js:212:10)\n' +
  '    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)'
```

**Comment by beliaev-maksim** [comment]
relation also seems to be created:
```
electron_release_server=> \dt
                    List of relations
 Schema |  Name   | Type  |            Owner
--------+---------+-------+------------------------------
 public | asset   | table | electron_release_server_user
 public | channel | table | electron_release_server_user
 public | flavor  | table | electron_release_server_user
 public | version | table | electron_release_server_user
(4 rows)
```

**Comment by beliaev-maksim** [comment]
issue is found,

I will fix the documentation and make a PR

**Comment by prv123** [comment]
@beliaev-maksim can you please help me out how you resolved this error

**Comment by beliaev-maksim** [comment]
@prv123 

sure, 
have you looked at PR [242](https://github.com/ArekSredzki/electron-release-server/pull/242) ?

you can pull a branch from my repo: https://github.com/beliaev-maksim/electron-release-server/tree/beliaev_update_docs

**Comment by prv123** [comment]
@beliaev-maksim Thanks a lot, as per your instruction i have to just update my session.js adapter settings for postgresql and it worked like a charm...

**Comment by beliaev-maksim** [comment]
@prv123 

glad to hear!
so my instruction was battle tested :)
